### ISSUE TITLE
ToggleDevice command incomplete

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#167]
https://github.com/progetto-oop-22-23/OOP22-HOMER/blob/6e162ee87f0dadc0261791d6a2d98e779ef0e72a/src/main/java/homer/controller/command/ToggleDevice.java#L9-L14

@michelececcacci should be updated, I can commit if you want
```java
        controller.getDeviceManager().toggleDevice(deviceId);
```

**Comment by michelececcacci** [comment]
i'll commit your code suggestion and merge

**Comment by michelececcacci** [comment]
yeah, commit it. no problem.
