### ISSUE TITLE
Package separation

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#31]
@aleemont1 @michelececcacci 
We need to split the classes in packages in a coherent way.
This can be a WIP as we work on the features.

Ideas:
- api
  - ?
- controller
- device / model
  - device?
    - deviceImpl.java
- view
  - dashboard
  - graphs
  - ?
- common
- core (for the simulation?)

**Comment by michelececcacci** [comment]
what would we put in api? putting all the interfaces in there does not feel very good to me

**Comment by aleemont1** [comment]
Yup, was thinking abt it, will tell youif I have any ideas, let's start by something basic as you proposed, we'll evolve this as we work.

**Comment by smagnaniuni** [comment]
I think we should remove the api package and put together the interfaces with the implementations.
For example:
- Controller, DeviceInfo, DeviceId should go in homer.controller, and maybe split in additional subpackages.
- DeviceView should go in homer.view
- Device, ToggleableDevice, etc. should go in homer.model

**Comment by aleemont1** [comment]
> I think we should remove the api package and put together the interfaces with the implementations. For example:
> 
> * Controller, DeviceInfo, DeviceId should go in homer.controller, and maybe split in additional subpackages.
> * DeviceView should go in homer.view
> * Device, ToggleableDevice, etc. should go in homer.model
> * Other devices could then go for eg. homer.model.deviceA ?

I like this, it looks well organized

**Comment by michelececcacci** [comment]
> > I think we should remove the api package and put together the interfaces with the implementations. For example:
> > 
> > * Controller, DeviceInfo, DeviceId should go in homer.controller, and maybe split in additional subpackages.
> > * DeviceView should go in homer.view
> > * Device, ToggleableDevice, etc. should go in homer.model
> > * Other devices could then go for eg. homer.model.deviceA ?
> 
> I like this, it looks well organized

same

**Comment by aleemont1** [comment]
This should be done asap, before merging new features.
