### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#47]
@aleemont1 @michelececcacci 
We need to clearly define the git workflow and write it down.
How do we pull new features?
How do we branch out?
Where do we create the pull requests to?

**Comment by aleemont1** [comment]
For every new feature we may:
- create a new branch (e.g. feature/awsome_feature)
- pull --rebase from dev
- open a PR into dev
- resolve the PR
- merge in dev

But we need to be faster in merging in dev, otherwise we'll get stuck.

**Comment by smagnaniuni** [comment]
We need to define what is the use of the distinction between main and dev.

**Comment by aleemont1** [comment]
> We need to define what is the use of the distinction between main and dev.

We'll push in main as soon as we get a working version of HOMER, so when a simulation (even if it's very basic) can be started. In other words, when any user can actually install and start HOMER.

**Comment by smagnaniuni** [comment]
That sounds like a release, but we can push to main sometimes I guess.
Another thing, to avoid issues we should never squash in pull requests.

**Comment by aleemont1** [comment]
> That sounds like a release, but we can push to main sometimes I guess. Another thing, to avoid issues we should never squash in pull requests.

I agree, you should only squash or drop useless/wrong commits in your local repo to avoid issues.

**Comment by aleemont1** [comment]
> That sounds like a release, but we can push to main sometimes I guess. Another thing, to avoid issues we should never squash in pull requests.

But after we release the firt version in main we will implement new working features every time we implement a new one, in dev we'll probably put more experimental stuff too. So if we have a new feature which might break something in the app, we should keep it in dev until we fix the issues, but if the new feature works as expected we can merge it in main with no problems. The first push in main will obv look like a release, subsequent ones will be new features introductions.

**Comment by aleemont1** [comment]
Btw I suggest using Discussions for these topics instead of issues.

**Comment by aleemont1** [comment]
Can we close this?
