### ISSUE TITLE
Controller interface review

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#50]
@michelececcacci @aleemont1

**Comment by smagnaniuni** [comment]
WIP

Interface changes required

`void connectDevice(??? device);` review the device type, it's not an MVC architecture if the view passes a device object

`getDevices()` -turn into> `getConnectedDevices();`

add a method that returns a list/set of connectable devices to the view
`??? getConnectableDevices();`
from the view you can then select which device to connect, call connectDevice, and the controller will know which device to create

`signalDevice()` should be moved to separate observer interface, the controller will implement said interface, and the view will use the observer to call the method

**Comment by smagnaniuni** [comment]
Idea
Separate different areas of the controller
```
interface Controller {
  + getDeviceManager(): DeviceManager
  + getScheduler()
  + getLogger()
  + ?
}

interface DeviceManager {
  + connectDevice(?)
  + disconnectDevice(uuid)
  + getConnectedDevices(): DeviceView ? 
  + getConnectableDevices(): ?

  + signalDevice(?)
  + toggleDevice(?) ?
  + setAdjustableDevice(?) ?
}
```

**Comment by michelececcacci** [comment]
> Idea Separate different areas of the controller
> 
> ```
> interface Controller {
>   + getDeviceManager(): DeviceManager
>   + getScheduler()
>   + getLogger()
>   + ?
> }
> 
> interface DeviceManager {
>   + connectDevice(?)
>   + disconnectDevice(uuid)
>   + getConnectedDevices(): DeviceView ? 
>   + getConnectableDevices(): ?
> 
>   + signalDevice(?)
>   + toggleDevice(?) ?
>   + setAdjustableDevice(?) ?
> }
> ```

sounds like a good idea

**Comment by michelececcacci** [comment]
>To create a device send said type.

will all the other parameters be selected by default?

**Comment by michelececcacci** [comment]
```plantuml
interface Controller {
  + getDeviceManager(): DeviceManager
  + getScheduler()
  + getLogger()
  + ?
}

interface DeviceManager {
  + connectDevice(?)
  + disconnectDevice(uuid)
  + getConnectedDevices(): DeviceView ? 
  + getConnectableDevices(): ?

  + signalDevice(?)
  + toggleDevice(?) ?
  + setAdjustableDevice(?) ?
}
```

**Comment by smagnaniuni** [comment]
# Architecture

```
class CoreImpl {
	loop() {
		controller.updateTick(dt)
	}
}

class ControllerImpl {
	- Map<ID, Device>
	- List<View> views

	+ updateTick() {
		devices.foeach(d -> d.updateTick(dt)
		views.foreach(v -> v.updateDeviceState(...)
	}

    + execute(enum/cmd/string) {
        switch(cmd) {
            ...
        }
    }

    + getCommands(): Set<Command>
}

interface Command {
    + execute(): void
}

class CreateLight() implements Command {
        ' constructor
        + CreateLight(Map devices, Map views)

        + execute() {
            devices.add(new Light())
            views.foreach(v -> v.addDevice(LIGHT)
        }
}


interface View {
    + addDevice(enum/string)
    + removeDevice(UUID id)
	+ updateDeviceState(UUID id, ? state)
}

class ViewImpl {
    - Map<UUID, DeviceView> deviceViews
}

interface DeviceView {
	+ getType = slider/toggleable
	+ getState()
}
```

## what to pass to the view?
- custom protocol? eg. string/json/yaml
```
"slider:value"
"toggled:on"

"slider;1;value;"
"slider;3;value;value;value"
"slider;3;value;value;value;toggle;1"
```

```
{
    type = ""
    {
        value = x
    }
    {
        parameterName = ""
        value = y
    }
}
```

- DeviceView object implementation?

**Comment by michelececcacci** [comment]
record Somecommand() implements Command  {

	@override
	public execute(Controller controller) {
		controller.removeDevice();
	}

}

public ControllerImpl {
	{
		...
		Command c;
		c.execute(this);
		...
	}
	receiveCommand(Command command) {

	}	
}

DeviceViewX implements DeviceView {
	controller.receiveCommand(new SomeCommand())
}
