### ISSUE TITLE
[PRIORITY] DeviceInfo creation and storage

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#59]
Maybe the ID should be created and stored in the controller.
What about the device type? Should it be decided by the controller or reported by the device?
If everything is done at the controller level, then we can scrap all the interface getters for info and just store it in the controller, since there's no point for the device to store that info.

**Comment by michelececcacci** [comment]
>If everything is done at the controller level, then we can scrap all the interface getters for info and just store it in the controller, since there's no point for the device to store that info.


i feel like having them associated with the devices makes more sense logically, and could be better for logging
