### ISSUE TITLE
Windows CI and line endings

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/OOP22-HOMER#79]
@michelececcacci 

The windows CI is complaining about line endings

```
Error: eckstyle] [ERROR] D:\a\HOMER\HOMER\src\main\java\homer\App.java:1: CRLF and CR line endings are prohibited, but this file uses them. [RegexpMultiline]
Error: eckstyle] [ERROR] D:\a\HOMER\HOMER\src\main\java\homer\App.java:1: Expected line ending for file is LF(\n), but CRLF(\r\n) is detected. [NewlineAtEndOfFile]
```

Every file is correctly using LF. `git ls-files --eol`
Seems like the CI is converting them to CRLF on checkout?
Maybe we need to add this to .gitattributes?

```
*	text=auto
```

This probably won't fix the problem since it deals with the files in the git index, while the problem happens on checkout I guess

**Comment by michelececcacci** [comment]
not really sure on what to do honestly, i will look into it

**Comment by smagnaniuni** [comment]
On windows it's normal behavior to convert from LF to CRLF on checkout (the working tree) and normalizing back to LF in the index (atleast when autocrlf=true)
So maybe

```
* text eol=lf
```

I say we can ignore it for the moment, just don't risk messing up everything, it can always be manually tested on a windows vm.

**Comment by michelececcacci** [comment]
yeah, sounds like the best option for now
