### ISSUE TITLE
Limit class should treat Number class and not just int.

### ISSUE THREAD

**Issue by aleemont1** [progetto-oop-22-23/OOP22-HOMER#80]
I think it'd be better for it to treat [Numbers](https://www.cs.usfca.edu/~cs272/javadoc/api/java.base/java/lang/Number.html) and not just integers.

**Comment by smagnaniuni** [comment]
Unfortunately Number is not comparable, so even avoiding the use of Math.min/max it would not be possible, individual types should be used (can be overloaded)

**Comment by smagnaniuni** [comment]
Just let me know which types do you need
-float
-double
?
and I will add them

**Comment by aleemont1** [comment]
double for sure, if I'll need floats I'll let you know.
