### ISSUE TITLE
Make electrical meter work in real time

### ISSUE THREAD

**Issue by aleemont1** [progetto-oop-22-23/OOP22-HOMER#83]
I'm thinking of a way of using the electrical meter in real time. 
Should it remain as it is now, and we'll use it in the main loop? I still didn't get the functionality updateTick object. Shoul I implement it in Outlet? Or in the meter itself? Can you help me with that?

@smagnaniuni @michelececcacci

**Comment by aleemont1** [comment]
@smagnaniuni @michelececcacci Can you help me with this, too? No pressure, just a remainder :)

**Comment by aleemont1** [comment]
Okay, I thought and built the electrical meter as part of the controller. In this case I need to implement DynamicObject in Outlet class, implementing updateTick in there, using it to update their state. But for doing that I need the plugged device to implement the consumePower method, thus create the PoweredDevice interface, after that I'll proceed integrating the Outlets with the updateTick method which whould make no sens in this state.
Does it seem reasonable?
For instance I thought of it like this:
In Outlet class:
```
@Override
public void updateTick(final Duration dt) {
    final double oldCons = this.getConsumption();
    final double newCons = this.getDevice().consumePower() * dt.toMillis() * Outlets.MY_SCALE_FACTOR;
    this.setState(newCons);
}
```
Did I get something wrong?

**Comment by smagnaniuni** [comment]
Seems fine, if `consumePower` would return watts, the consumption would be the watthours, or whatever, that is the general idea.

**Comment by aleemont1** [comment]
After merging #110, the `Outlet` class will be modified accordingly, in order to complete the `ElectricalMeter` and be able to log the power consumption of the various outlets irt.

The `ElectricalMeter` only has access to outlets, which will work as an intermediate between the Powered Devices and the Meter. 

My idea is to set the state of the `Outlet` to `myPoweredDevice.getInstantConsumption()` if the `Outlet` has a `PoweredDevice` plugged in, the `ElectricalMeter` will periodically check the state of the Outlets (which is going to be updated in the updateTick() method, i guess), and require the various to be performed from them (e.g. cutting power eccetera). I will produce a UML schema and some code for it in the following days.

**Comment by aleemont1** [comment]
> You can calculate it with updateTick I think.

ElectricalMeter is part of the controller, I thought updateTick was meant to be used in the model(?).
